# Generated by Django 5.1.3 on 2024-12-03 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoflash_app', '0002_conteudo_flashcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='conteudo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autoflash_app.conteudo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to=settings.AUTH_USER_MODEL),
        ),
    ]
