# Generated by Django 5.1.3 on 2024-12-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoflash_app', '0003_alter_flashcard_conteudo_alter_flashcard_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='intervalo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='prox_revisao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
