# Generated by Django 5.1.3 on 2024-12-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoflash_app', '0004_flashcard_intervalo_flashcard_prox_revisao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='prox_revisao',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='eficacia',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='intervalo',
            field=models.IntegerField(default=0),
        ),
    ]
