# Generated by Django 5.1.3 on 2024-12-05 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoflash_app', '0006_flashcard_next_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='next_review',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
