# Generated by Django 5.1.3 on 2024-12-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoflash_app', '0007_alter_flashcard_next_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='usuariointervalo',
            field=models.IntegerField(default=1),
        ),
    ]
